spring:
  application:
    name: email-service-for-booking
  mail:
    host: smtp.gmail.com
    port: 587
    username: turfease.dev@gmail.com
    password: pelzlxrxyhtbvigp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"